version: '3.8'

services:
  app:
    build: .
    container_name: kaajasse_app
    volumes:
      - ./:/var/www/html:rw
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    container_name: kaajasse_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: kaajasse_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
